A={10,20,30,40}
B={30,40,50,60}
print("Set A:", A)
print("Set B:", B)
A.add(70)
print("After Add:", A)
A.update([80,90])
print("After Update:", A)
A.remove(20)
print("After Remove:", A)
A.discard(100)
print("After Discard:", A)
print("Union:", A.union(B))
print("Intersection:", A.intersection(B))
print("Difference:", A.difference(B))
print("Symmetric Difference:", A.symmetric_difference(B))
copy_set = A.copy()
print(copy_set)
print("Maximum:", max(A))
print("Minimum:", min(A))
print("Sum:", sum(A))
print("Length:", len(A))