numbers = (10,20,30,20,40,50)
print("Tuple:", numbers)
print(numbers[2])
print(numbers[1:5])
print("Length:", len(numbers))
print("Count of 20:",numbers.count(20))
print("Index of 40:",numbers.index(40))
print("Maximum:",max(numbers))
print("Minimum:",min(numbers))
print("Sum:",sum(numbers))
print("Average:",sum(numbers)/len(numbers))
print(30 in numbers)
new_list=list(numbers)
print(new_list)