name=input("Enter your name:")
age=int(input("Enter your age:"))
college=input("Enter your College name:")
cgpa=float(input("Enter your cgpa:"))
branch=input("Enetr Your Branch:")
skills=input("Enter the skills you have:")
dream_company=input("What is Your Dream Company?")
expected_Salary=int(input("What is your expected salary?"))
city=input("Enter the city you live:")
phone_number=int(input("Enter Your Mobile number:"))
print("========Student Profile=========")
print("My name is",name)
print("I am",age,"years old")
print("I have completed my B.Tech in",college)
print("My cgpa is",cgpa)
print("My branch is",branch)
print("The skills I have are",skills)
print("My dream company is",dream_company)
print("My Expected Salary is",expected_Salary,"per annum")
print("I live in",city)
print("My phone number is",phone_number)
print("=================================")
