import numpy as np
arr = np.array([10, 20, 30, 40, 50])
# sum()
print("Sum")
print(np.sum(arr))
# mean()
print("\nMean")
print(np.mean(arr))
# max()
print("\nMaximum")
print(np.max(arr))
# min()
print("\nMinimum")
print(np.min(arr))
# argmax()
print("\nArgmax")
print(np.argmax(arr))
# argmin()
print("\nArgmin")
print(np.argmin(arr))
# sort()
print("\nSort")
arr2 = np.array([40, 10, 70, 20, 50])
print(np.sort(arr2))
# sqrt()
print("\nSquare Root")
print(np.sqrt(arr))
# power()
print("\nPower")
print(np.power(arr, 2))
# abs()
print("\nAbsolute")
arr3 = np.array([-10, -20, 30, -40])
print(np.abs(arr3))
# sin()
print("\nSin")
print(np.sin(arr))
# cos()
print("\nCos")
print(np.cos(arr))
# log()
print("\nLog")
print(np.log(arr))
# exp()
print("\nExponential")
print(np.exp(arr))
# unique()
print("\nUnique")
arr4 = np.array([10, 20, 20, 30, 30, 40, 50])
print(np.unique(arr4))