import numpy as np
# rand()
print("Random Float Numbers")
print(np.random.rand(5))
# randn()
print("\nRandom Normal Numbers")
print(np.random.randn(5))
# randint()
print("\nRandom Integers")
print(np.random.randint(1, 20, 5))
# choice()
print("\nChoice")
print(np.random.choice([10, 20, 30, 40, 50]))
# seed()
print("\nSeed")
np.random.seed(10)
print(np.random.randint(1, 20, 5))
np.random.seed(10)
print(np.random.randint(1, 20, 5))
# shuffle()
print("\nShuffle")
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)
# permutation()
print("\nPermutation")
arr = np.array([10, 20, 30, 40, 50])
print(np.random.permutation(arr))